name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifier le code du dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configurer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13' # Assurez-vous que cette version est disponible

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Assurez-vous que ce fichier existe

      # Étape 4 : Exécuter les tests
      - name: Run tests
        run: |
          pytest # Remplacez par votre commande de test si nécessaire

      # Étape 5 : Construire l'image Docker
      - name: Build Docker image
        run: |
          docker build -t $DOCKER_USERNAME/flaskapp:latest .

      # Étape 6 : Connecter Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Étape 7 : Pousser l'image sur Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push $DOCKER_USERNAME/flaskapp:latest
